theme: "hugo-PaperMod"
baseURL: 'essbee.netlify.app'
languageCode: en-us
title: EssBee
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true
    
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: EssBee
    description: "Thoughts and Notes of a Marine Biologist and Plant Physiology PhD student"
    keywords: [Blog, Notes, Digital Garden, Marine Biology, Plant Physiology, Portfolio, PaperMod]
    author: Sepehr Bardi
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        assets:
         favicon: "static/favicon.ico"
 #        favicon16x16:  "static/favicon-16x16.png"
         favicon32x32:  "static/favicon-32x32.png"
         apple_touch_icon:  "static/apple-touch-icon.png"
         

    label:
        text: "EssBee"
       # icon: static/apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Mind of a biologist"
        Content: Welcome to EssBee (SB) - **Sepehr Bardi**'s digital garden. SB is a marine biologist and a plant physiology PhD student with interests in microbial symbioses and the deep ocean.

    socialIcons:
        - name: email
          url: "sepehr.nik96@gmail.com"
        - name: linkedin
          url: "https://www.linkedin.com/in/sepehrnik/"
        - name: github
          url: "https://github.com/sebardi"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/<path_to_repo>/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: about
          name: About
          url: /about/
          weight: 20
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 40
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 40
        - identifier: search
          name: Search
          url: /search/
          weight: 50
        - identifier: notes
          name: Notes
          url: /note/
          weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai